film and user rest controllers
bvprod/java-filmorate pull request #5
Opened 2024-03-09 11:01 UTC by bvprod

2024-03-10 03:38 UTC, dgumich requested changes

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895,12,28))) {
Код на строках 24-26 надо вынести в отдельный метод

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashSet<Film> films = new HashSet<>();
А как будешь доставать фильм? В плане запросят у тебя фильм с таким то айди, то это весь хеш сет придется перебирать, что бы найти его? Используй как было с канбаном: хэшмепу, где ключ - айдишник, а значение - сам фильм

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Set<Film> getFilms() {
Обычно в работе по ресту используют массив или лист, но не сет. Так что лучше возвращай список.

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    private final HashSet<User> users = new HashSet<>();
Аналогично, хешсет лучше заменить на хешмапу

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +    public Set<User> getUsers() {
И тут используй список, а не сет

2024-03-10 03:38 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
А где тесты?=) Нет ни одного теста. Даже по тз написано: 
Тестирование
Добавьте тесты для валидации. Убедитесь, что она работает на граничных условиях.

2024-03-12 06:39 UTC, bvprod commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        if (film.getReleaseDate().isBefore(LocalDate.of(1895,12,28))) {
Исправил, вынес в отдельный метод checkFilmReleaseDate

2024-03-12 06:39 UTC, bvprod commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashSet<Film> films = new HashSet<>();
Заменил на хэшмапу

2024-03-12 06:40 UTC, bvprod commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public Set<Film> getFilms() {
Исправил возвращаемое значение на список

2024-03-12 06:40 UTC, bvprod commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
>  public class FilmController {
Добавил тесты

2024-03-13 03:13 UTC, dgumich approved these changes

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private static final LocalDate earliestFilm = LocalDate.of(1895, 12, 28);
private static final находится в самом начале класса. Это по code style
![image](https://github.com/bvprod/java-filmorate/assets/42573998/4e7bc9af-8d38-457a-8312-9c65469d1926)

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        } else {
Блок else не нужен, можешь написать код без него, потому что в блоке if есть return.
Старайся избегать ненужных блоков, это упрощает восприятие кода.

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        } else {
Здесь тоже можно без блока else

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +            log.warn("Фильм с id " + film.getId() + " не найден");
Обычно такие сообщения так же логируют с уровнем info

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +            throw new ValidationException("Пользователь с id " + user.getId() + " не найден");
Не совсем подходящее исключение. Всё-таки пользователя нет, а не ошибка валидации. Лучше сделать кастомное свое, но пока ок.

2024-03-13 03:13 UTC, dgumich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
А это что такое HashMap<Integer, Film> films ? =) Почему не используешь интерфейс Map, а сразу HashMap?

2024-03-22 15:38 UTC, merged